### ISSUE TITLE
Feature: User can view all their ride logs on their profile page

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all their ride logs and bike information on their profile page as well as a map that displays places they've ridden.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
user can click on the My Rides tab or My Bikes tab to view info. A map will be displayed containing markers of where the user has logged rides. User can click on a ride log underneath the My Rides tab to show a full log of the ride.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Profile Screen (1)](https://user-images.githubusercontent.com/103209321/189974181-a5e1304d-edd8-4d04-90ae-2e02e0bd417e.png) ![view users rides (1)](https://user-images.githubusercontent.com/103209321/189974209-0bd91435-f7d8-4e28-bc3b-13f93a48c9fc.png)
![View log page](https://user-images.githubusercontent.com/103209321/191102415-ec06d2ea-3b37-4a44-badf-29fc74fe7b7e.png)

![Profile Page](https://user-images.githubusercontent.com/103209321/189973833-141378c7-d68f-4e5a-9959-95590d9b6108.png)
![View All Rides](https://user-images.githubusercontent.com/103209321/189973857-873ae997-2d2e-47c2-96ad-91e33cd2fc3a.png)
![Succesfully created log (1)](https://user-images.githubusercontent.com/103209321/191102522-b7d0e7f7-6b61-457c-9b13-20b6e0feeb44.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...add a Get request that pulls the location, caption, date, and photoUrl from the database.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...Make the My Bikes & My Rides tabs clickable, and when they expand to show a list of locations they've ridden at.
- [x] Fetch the rideLogs from the server.
- [x] Once a specific location is clicked swap views to a full info page that contains the Photo, Location, Date, and Caption of that clicked location.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
