### ISSUE TITLE
Feature: User can Sign Up

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up for an account to log their rides.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
On the home page you can press the sign up button which will redirect you to a Sign Up page. User enters a username and password to create an account.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![after Sign Out](https://user-images.githubusercontent.com/103209321/189975789-60379cf3-64fb-47ec-8ea4-f4f9f89ccb60.png) ![Create Accoun page](https://user-images.githubusercontent.com/103209321/189975934-cbe38baa-af29-487c-94dc-8caadee2a80f.png)

![after sign out page](https://user-images.githubusercontent.com/103209321/189975537-de69da9e-a5b1-40cb-ae2b-f1e9f9225ed9.png)
![Create Account page](https://user-images.githubusercontent.com/103209321/189976044-bb0ebaec-eaf0-498a-9659-9d1cf6fa8a01.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...add a `POST` method that inserts the username into the database, as well as the password once its been `hashed` using `argon2`.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...be the Home screen and match output of Figma.
- [x] Add a map to home screen(since no one is signed in yet have no markers shown).
- [x] Once the Sign Up button is clicked swap to a create account form.
- [x] When the username and password are inputted and the Register button is clicked send a `fetch` request to the server to send the data to the database.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
