### ISSUE TITLE
Feature: User can Sign In

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign in to their account to view / add ride logs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
On the sign in page enter a valid username and password to get signed in. If a valid user you'll be redirected to profile page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Sign in page](https://user-images.githubusercontent.com/103209321/189977742-32a42435-e641-458a-8b11-a31961fd9268.png)
![Sign In Page (1)](https://user-images.githubusercontent.com/103209321/189977769-0c794f05-9af2-420b-95bc-01b03cab62ee.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...make a `POST` request that pulls matching username and password from the database, and then checks to see if the password and hashedPassword match.
- [x] If they do match a token will be assigned to the user.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update Home Page component to ...swap to a sign in form if the user clicks on the Sign In button.
- [x] Once someone clicks Register when they create an account the view will swap to Sign In form.
- [x] Update Auth Form to change if the hash route is set to 'sign-in'.
- [x] Once the user presses Log In swap to that users profile view.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
