### ISSUE TITLE
Feature: User can SIgn Out

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign out of their account.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the profile icon on the Navbar to open a modal with a tab option to sign out. Once pressed you'll be redirected to the home page.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Profile Icon Click](https://user-images.githubusercontent.com/103209321/189979247-1b8e1a69-be6e-4427-9272-545e9208bf48.png)
![Profile Icon Clicked](https://user-images.githubusercontent.com/103209321/189979266-605608ab-fce5-4cbe-875d-d92c08a4d476.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update App.Jsx to have a sign out method that removes token from local storage as well as setting user to null.
- [x] Update NavBar component to ...When the profile icon is clicked show an App Drawer.
- [x] Have 4 items in the App Drawer, View Profile, Add a Ride Log, Add a Bike, and SIgn Out.
- [x] When any tabs are clicked the page should swap to the appropriate page.
- [x] Once sign out is clicked remove token from local storage and swap to the Home Screen.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
