### ISSUE TITLE
Feature: User can view a map with markers for all logged rides

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a map that shows markers of locations or trails they've ridden at.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a User is signed in and ride logs have been created a map will display showing markers of those logged locations. On the home screen if no user is signed in it will display a normal map.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Profile Screen (2)](https://user-images.githubusercontent.com/103209321/189980482-529bbeec-6102-47fe-92ab-4405b8396071.png)
![Profile Page (1)](https://user-images.githubusercontent.com/103209321/189980503-163bc8bb-6bf0-48d9-8996-2dbaba387854.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...include lat & lng coordinates to be able to plot on the map.
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...send a GET request to the database and pull the coordinates from each rideLog.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...match the output of the figma template.
- [x] display a map using Google Maps that contains markers of places ridden at according to the ride logs.
- [x] inside of componentDidMount fetch the rideLogs from the server.
- [x] Make an accordion to be used later to show rideLogs and bike info.
- [x] Update Log Successful component to ...Show the profile page once the view logs button is clicked.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
