### ISSUE TITLE
Feature: User can add info about their Mountain Bike

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add the Make, Model, and Year of their Mountain Bike.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When the profile icon is clicked press the Add a Bike tab, when pressed it will redirect you to a Add Bike Info Form where you can then input your bike information.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add Bike form](https://user-images.githubusercontent.com/103209321/189981462-9abb51e8-c1c9-458f-b1c3-ca455c244cc2.png) ![Bike form with info](https://user-images.githubusercontent.com/103209321/189981487-6bcbfc1d-2bb0-4d3d-89fb-19a040f0cf43.png)
![after bike info submit](https://user-images.githubusercontent.com/103209321/189981512-ba447839-49d7-4b8e-a55d-5c4fbd5650eb.png)

![Bike Info form](https://user-images.githubusercontent.com/103209321/189981662-e6a5c3bf-74ef-4daf-8879-107e916e4413.png)
![Bike Info form with data](https://user-images.githubusercontent.com/103209321/189981678-87e9213a-523e-43b0-9033-b9859f71fe71.png)
![Bike Succesfully Saved](https://user-images.githubusercontent.com/103209321/189981694-b0f72321-0e7a-4e6f-a1d1-0a0aff80b4e1.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server/index.js` to ... make a `POST `request that pulls data from the add bike form and inserts it into the bikeInfo  table.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...render the page to match the output of the Figma design.
- [x] Listen for `changes `in the input forms on the page.
- [x] Update the values to whatever is being inputted. 
- [x] Listen for the `submit` event and use `event.preventDefault `to not reload the page.
- [x] Pressing submit should redirect to a Bike Added Successfully page.
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
