### ISSUE TITLE
Feature: User can Create a ride log

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/final-project#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a ride log of a location or MTB trail they've ridden at, log the date they visited, add a caption or comment, and add a photo.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

when logged in press the profile icon then press on the Add a Log tab. Once pressed you'll be redirected to the create a log page that contains a form to input ride data.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Add Log form](https://user-images.githubusercontent.com/103209321/189983032-cb9541ac-8eaa-4d6c-a2ad-35903c143493.png) ![Log with full info](https://user-images.githubusercontent.com/103209321/189983055-16abeed2-6062-4a80-9f20-49403e8a566f.png)
![after log submit](https://user-images.githubusercontent.com/103209321/189983103-682ede0d-2625-4fb5-a187-215de55f36de.png)

![Add a ride log form](https://user-images.githubusercontent.com/103209321/189983207-00bb568b-2429-4365-8973-5cb25760a073.png)
![Ride Log form with data](https://user-images.githubusercontent.com/103209321/189983218-f658b878-92ab-48db-a786-05bf01079c2e.png)
![Succesfully created log](https://user-images.githubusercontent.com/103209321/189983227-894aede2-9df9-4d0d-aa6a-ed69df5b6b95.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...using dbdesigner provided code to display tables and columns
- [x] Update `data.sql` to ...insert a dummy user for development.
- [x] create database and run pgweb to view live database.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...add a `POST` request that pulls the data from the submitted form and checks for valid input for each input or else an error will be thrown. If all input is valid then insert it into our `rideLogs` table in our database.

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...render the page to match the output of the Figma design. Listen for `changes` in the input forms on the page, and update the values to whatever is being inputted. listen for the `submit` event and use `event.preventDefault` to not reload the page. Pressing submit should redirect to a Log Created Successfully page.
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
