### ISSUE TITLE
Feature: User can delete their ride log

### ISSUE THREAD

**Issue by alvarodiazjr** [alvarodiazjr/final-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete their ride logs.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When looking at your logs full info screen press the 3 bars icon on the bottom left. When pressed a Modal will pop up asking whether you want to edit or delete the log. Press delete then another modal will pop up asking if you're sure you want to delete. Press Yes, Delete then the log will be deleted and you'll be redirected to a page saying the delete was successful.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![button click](https://user-images.githubusercontent.com/103209321/189986801-19572b90-8541-4ce0-9ee3-8faf766883be.png)![Page after delete button click](https://user-images.githubusercontent.com/103209321/189986848-5016e48c-b820-4983-bb5d-28e6c8ed572b.png)
![after delete log click](https://user-images.githubusercontent.com/103209321/189986882-2dd13f03-c450-4899-8aed-cf7a3bef9842.png)

![After button is clicked](https://user-images.githubusercontent.com/103209321/189986960-cd9c6f19-a59a-4f35-93f3-eb700f94ba38.png)
![After Delete Button is clicked](https://user-images.githubusercontent.com/103209321/189987005-c567ae92-07da-4dcd-8f02-bb0d8dc55628.png)
![Succesfully deleted log](https://user-images.githubusercontent.com/103209321/189987029-e6f6681a-6a84-4590-8532-48f7c08f9aa3.png)
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to ...Add a `delete` method that deletes the log at the`logId` number.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update FullLog component to ...Add an pencil Icon to the bottom right of the RideLog info card.
- [x] Add a `modal` to be displayed once the icon is clicked.
- [x] If Go Back is clicked remove modal and stay on the same Ride Log screen.
- [x] If Delete is pressed the modal will change asking if you're sure you want to delete the log.
- [x] Once Yes, Delete is pressed send a `fetch` request to the server to delete the log from the database.
- [x] A successful delete page will show where you can create another log or view logs.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
